//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleReviewer
    {
        public int articleId { get; set; }
        public int reviewerId { get; set; }
        public string revisionText { get; set; }
        public Nullable<int> grade { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual User User { get; set; }
    }
}
