//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.ArticleAuthors = new HashSet<ArticleAuthor>();
            this.ArticleReviewers = new HashSet<ArticleReviewer>();
            this.Files = new HashSet<File>();
        }
    
        public int id { get; set; }
        public Nullable<int> conferenceId { get; set; }
        public int stateId { get; set; }
        public string summary { get; set; }
        public Nullable<bool> accepted { get; set; }
        public System.DateTime submissionDate { get; set; }
    
        public virtual ArticleState ArticleState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleAuthor> ArticleAuthors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleReviewer> ArticleReviewers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<File> Files { get; set; }
        public virtual Conference Conference { get; set; }
    }
}
