//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConferenceUser
    {
        public int conferenceId { get; set; }
        public int userId { get; set; }
        public System.DateTime registrationDate { get; set; }
    
        public virtual Conference Conference { get; set; }
        public virtual User User { get; set; }
    }
}
