//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int id { get; set; }
        public int articleId { get; set; }
        public byte[] file1 { get; set; }
        public System.DateTime insertionDate { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
